### PR TITLE
Handle zero-area and display: none cases for v2 release branch

### PR DESCRIPTION
**Pull request by asakusuma**
Attempts to satisfy the spec: https://www.w3.org/TR/intersection-observer/#update-intersection-observations-algo

isIntersecting, non-zero area, and display:nonen are all related, so fixing in one swoop.

Fixes:
#93
#73

Related issues:
w3c/IntersectionObserver#69
w3c/IntersectionObserver#222

### CODE REVIEW

**Comment by asakusuma** [comment]
v2 equivalent of https://github.com/linkedin/spaniel/pull/102

**Comment by lynchbomb** [comment]
lgtm

**Comment by guidobouman** [comment]
This is not compliant with Steps 7 & 8:

```
7. Let isIntersecting be true if targetRect and rootBounds intersect or are edge-adjacent, even if the intersection has zero area (because rootBounds or targetRect have zero area); otherwise, let isIntersecting be false.

8. If targetArea is non-zero, let intersectionRatio be intersectionArea divided by targetArea.
Otherwise, let intersectionRatio be 1 if isIntersecting is true, or 0 if isIntersecting is false.```

Particularly: support for zero space elements is removed.

**Comment by asakusuma** [comment]
@guidobouman thanks for calling out the non-compliance.

@seanjohnson08 can you take a look at this non-compliance issue?

**Pull request merged**
